Update build.xm for scriptdef
Appirio/sfdc-ant-build-script pull request #1
Opened 2017-08-17 11:55 UTC by ashishappirio

Added a single script tag that can be called by specific tests targets just by passing login details.

2017-08-17 13:59 UTC, bruzzi requested changes
Thanks for creating the function to run specified tests - much cleaner!  I had a few minor comments and requests before we finalize.  

PS: With this new ant functionality, I see opportunities to modularize this entire build.xml file in the future!

2017-08-17 13:59 UTC, bruzzi commented on build.xml
> +		var username = attributes.get("cmcuser");
Let's more generically call this attribute "username"

2017-08-17 13:59 UTC, bruzzi commented on build.xml
> +		var password = attributes.get("cmcpass");
Let's more generically call this attribute "password"

2017-08-17 13:59 UTC, bruzzi commented on build.xml
> +    	    deployTask.setMaxPoll("5000");
Minor formatting issue, but looks like you have some spacing/tabbing issues between lines 37-44.

2017-08-17 13:59 UTC, bruzzi commented on build.xml
> +  <scriptdef name="scepcificTest" language="javascript">
Typo in name: "scepcificTest". Probably best to name this script as a verb (e.g., "runSpecifiedTests").

2017-08-17 13:59 UTC, bruzzi commented on build.xml
> +    <attribute name="cmcpass"/>
Let's more generically call this attribute "password"

2017-08-17 13:59 UTC, bruzzi commented on build.xml
> +    <attribute name="cmcuser"/>
Let's more generically call this attribute "username"

2017-08-17 13:59 UTC, bruzzi commented on build.xml
> +	<scepcificTest cmcuser="${cmc.full.username}" cmcpass="${cmc.full.password}" serverurl="${sandbox.serverurl}"/>
Typo "scepcificTest".  Update names of username/password attributes per earlier comments.

2017-08-17 13:59 UTC, bruzzi commented on build.xml
> +  	<scepcificTest cmcuser="${cmc.prod.username}" cmcpass="${cmc.prod.password}" serverurl="${prod.serverurl}"/>
Typo "scepcificTest".  Update names of username/password attributes per earlier comments.

2017-08-17 13:59 UTC, bruzzi commented on build.xml
> +	 <scepcificTest cmcuser="${cmc.dev.username}" cmcpass="${cmc.dev.password}" serverurl="${sandbox.serverurl}"/>
Typo "scepcificTest".  Update names of username/password attributes per earlier comments.

2017-08-17 13:59 UTC, bruzzi commented on build.xml
> +  	<scepcificTest cmcuser="${cmc.full.username}" cmcpass="${cmc.full.password}" serverurl="${sandbox.serverurl}"/>
Typo "scepcificTest".  Update names of username/password attributes per earlier comments.

2017-08-18 10:13 UTC, ashishappirio commented
Thanks Chris for your review on this, I've made the changes as suggested.

2017-08-18 18:08 UTC, merged