Update README.md
Appirio/sfdc-ant-build-script pull request #3
Opened 2017-08-21 05:42 UTC by ashishappirio

2017-08-30 02:13 UTC, bruzzi requested changes

2017-08-30 02:13 UTC, bruzzi commented on README.md
> +1. Ant version greater than 1.6, tested with 1.10.1 (latest version).
Let's kill the new Version Notes section and just move your bullet regarding ant version (line 5) as the first item under the Prerequisites section.

2017-08-30 02:51 UTC, ashishappirio commented
Done with the change.

2017-10-20 19:08 UTC, bruzzi approved these changes

2017-10-20 19:08 UTC, merged